spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/twitter-like
    username: mysqldatabase
    password: mysqldatabase
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false

server:
  port: 8080
